server:
  port: 10000

spring:
  jmx:
    enabled: false          # 禁用 JMX，解决冲突
  profiles:
    active: dev
  application:
    name: GatewayApplication  # 建议与 Nacos 中的服务名一致
  config:
    import:
      - nacos:sharding-spring.yaml
      - nacos:sharding-redis.yaml
      - nacos:sharding-logs.yaml
  cloud:
    nacos:
      config:
        server-addr: 192.168.150.104:8848
        file-extension: yaml
    gateway:
      routes:
        - id: ms
          uri: lb://media-service
          predicates:
            - Path=/ms/**
      default-filters:
        - StripPrefix=1
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "GET,POST,DELETE,PUT,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000